Upgrade parent to 14.10 #46
xwikisas/identity-oauth pull request #48
Opened 2024-10-18 14:21 UTC by ChiuchiuSorin

* modified parent  platform version to 14.10-1
* uploaded the documents from an instance of XWiki 14.10
* updated README.md
* checked for keywords and regex
* created the DefaultIdentityOAuthManagerUtils class to move functions from DefaultIdentityOAuthManager class to avoid the class fan out complexity error
* moved LifeCycle enum in it's own public class
* refactored DefaultIdentityOAuthManager class
* tested functionalities using integration Azure

2024-10-22 13:21 UTC, oanalavinia requested changes

2024-10-22 13:21 UTC, oanalavinia commented on ui/src/main/resources/IdentityOAuth/IdentityOAuthGeneralConfiguration.xml
> +        <classname>IdentityOAuth.OAuthProviderClass</classname>
Why should this be added?

2024-10-22 13:21 UTC, oanalavinia commented on ui/src/main/resources/IdentityOAuth/IdentityOAuthGeneralConfiguration.xml
> +        <idField>providerHint</idField>
Same

2024-10-22 13:21 UTC, oanalavinia commented on ui/src/main/resources/IdentityOAuth/IdentityOAuthGeneralConfiguration.xml
> -        <sql>select providerHint.value from XWikiDocument doc, BaseObject as obj, StringProperty as providerHint where doc.fullName = obj.name and obj.className = 'IdentityOAuth.OAuthProviderClass' a
Why this should be deleted?

2024-10-22 13:21 UTC, oanalavinia commented on ui/src/main/resources/IdentityOAuth/LoginUIExtension.xml
> +            const params = getURLParams(url);
You kept the wrong code. The other branch is the one that uses `URLSearchParams`, and not a custom method created for IR11 support (`getURLParams` method should be deleted)

2024-10-22 13:21 UTC, oanalavinia commented on ui/src/main/resources/IdentityOAuth/Translations.xml
> -  <content>
Why were these lines added as changes? You shouldn't add changes if they aren't needed, since it's breaking history (if I want to see when a translation was added, I would see this commit; maybe some spaces were indeed needed?)

2024-10-22 13:21 UTC, oanalavinia commented on ui/src/main/resources/IdentityOAuth/WebHome.xml
> -{{/velocity}}
Same for these lines

2024-10-24 06:30 UTC, ChiuchiuSorin commented on api/pom.xml
> +  <description>This is the XWiki-API part of the Identity OAuth App which allows single sign on to several others.
Without the space, the live was over 120 characters.

2024-10-24 06:44 UTC, oanalavinia commented on api/pom.xml
> +  <description>This is the XWiki-API part of the Identity OAuth App which allows single sign on to several others.
For a pom it can happen, no need to limit to 120characters
This description it's also displayed in the EM, isn't the new space displayed now there?

2024-10-24 09:21 UTC, oanalavinia requested changes

2024-10-24 09:21 UTC, oanalavinia commented on api/src/main/java/com/xwiki/identityoauth/internal/DefaultIdentityOAuthManagerInitiator.java
> +public class DefaultIdentityOAuthManagerInitiator
Maybe `IdentityOAuthProviderLoader` ? Because you are not handing IdentityOAuthManager, but the providers it manages

2024-10-24 12:05 UTC, ChiuchiuSorin commented on api/pom.xml
> +  <description>This is the XWiki-API part of the Identity OAuth App which allows single sign on to several others.
I'm not seeing a new space in EM, but I'll modify it to how it was.

2024-10-24 12:15 UTC, ChiuchiuSorin commented on api/src/main/java/com/xwiki/identityoauth/internal/DefaultIdentityOAuthManagerInitiator.java
> +public class DefaultIdentityOAuthManagerInitiator
I feel that `IdentityOAuthManagerInitiator` it's a more descriptive name as the class does more than just handling the providers.

2024-10-30 14:23 UTC, merged