Setting the Default provider in Identity OAuth to force the Identity Provider does not fully work #47
xwikisas/identity-oauth pull request #49
Opened 2024-10-18 14:23 UTC by ChiuchiuSorin

**This PR depends on the modifications made on #48** 

* created configuration classes for IdentityOAuthGeneralConfiguration
* replaced selecting the default provider the XWiki object with a call to the newly created configuration classes

2024-10-21 06:18 UTC, oanalavinia requested changes

2024-10-21 06:18 UTC, oanalavinia commented on README.md
> +* Minimal XWiki version supported: XWiki 14.10
Added by mistake

2024-10-21 06:18 UTC, oanalavinia commented on api/pom.xml
> +  </description>
Is this needed?

2024-10-21 06:18 UTC, oanalavinia commented on api/src/main/java/com/xwiki/identityoauth/IdentityOAuthScriptService.java
> +     * @return the set default provider.
I think you added `set` by mistake

2024-10-21 06:18 UTC, oanalavinia commented on api/src/main/java/com/xwiki/identityoauth/internal/DefaultIdentityOAuthManager.java
> +    private DefaultIdentityOAuthManagerUtils managerUtils;
Was this refactoring needed for this issue? It's a little harder to follow what changes were done for this PR and what is refactoring

Looking at your commits, it looks like you also added (by mistake?) a commit related to the 14.10 upgrade. Was this needed? Otherwise, it would be good to have a look at PRs after opening them, like doing a 'first review'

2024-10-30 16:28 UTC, oanalavinia requested changes

2024-10-30 16:28 UTC, oanalavinia commented on api/src/main/java/com/xwiki/identityoauth/IdentityOAuthScriptService.java
> +     * Get the set default provider from the Identity OAuth general configuration.
`Get the default provider value set on the Identity OAuth...` . WDYT?

2024-10-30 16:28 UTC, oanalavinia commented on api/src/main/java/com/xwiki/identityoauth/configuration/IdentityOAuthGeneralConfiguration.java
> + * @since 1.7.6
Since this will be included in the same release as https://github.com/xwikisas/identity-oauth/issues/46 , the next version will be 1.8

2024-10-30 16:28 UTC, oanalavinia commented on api/src/main/java/com/xwiki/identityoauth/IdentityOAuthScriptService.java
> +    public String getDefaultProvider()
I don't see where you are using it

2024-10-30 16:28 UTC, oanalavinia commented on api/src/main/java/com/xwiki/identityoauth/internal/configuration/IdentityOAuthGeneralConfigurationSource.java
> + * configuration of the main wiki.
> In case no configuration is found on the current wiki, it will use the configuration of the main wiki.

I'm not sure I understand this. In this configuration, the document it's a LocalDocumentReference, which is specific to the [current wiki](https://github.com/xwiki/xwiki-platform/blob/master/xwiki-platform-core/xwiki-platform-model/xwiki-platform-model-api/src/main/java/org/xwiki/model/reference/LocalDocumentReference.java#L27) , yet you specify that a fallback on the main wiki it's done. Also, when using it in the `DefaultIdentityOAuthGeneralConfiguration`, you specify this is the `mainConfiguration` (as if it's for the main wiki?)
So this `ConfigurationSource` should be for the main or the current wiki?
If you want to implement a fallback, you can check what was done on the [collabora side](https://github.com/xwikisas/application-collabora/blob/main/application-collabora-default/src/main/java/com/xwiki/collabora/internal/configuration/DefaultCollaboraConfiguration.java#L70). There, the default configuration uses 2 `ConfigurationSource`, one for [current wiki](https://github.com/xwikisas/application-collabora/blob/main/application-collabora-default/src/main/java/com/xwiki/collabora/internal/configuration/CollaboraConfigurationSource.java#L47) and one for the [main wiki](https://github.com/xwikisas/application-collabora/blob/main/application-collabora-default/src/main/java/com/xwiki/collabora/internal/configuration/MainCollaboraConfigurationSource.java#L54) and chooses what to return.

2024-10-31 08:16 UTC, ChiuchiuSorin commented on api/src/main/java/com/xwiki/identityoauth/IdentityOAuthScriptService.java
> +    public String getDefaultProvider()
It was overwritten during merge with main, I added the line.

2024-10-31 08:22 UTC, ChiuchiuSorin commented on api/src/main/java/com/xwiki/identityoauth/internal/configuration/IdentityOAuthGeneralConfigurationSource.java
> + * configuration of the main wiki.
`AbstractWikisConfigurationSource` is for those situations when is needed to check first the current wiki and then the main wiki as a fallback: https://jira.xwiki.org/browse/XWIKI-20195 . It's being used in [PDF viewer](https://github.com/xwikisas/xwiki-platform/blob/03d3ebeaea072fdc4e17f5aff0a5f7c0e5e6de8f/xwiki-platform-core/xwiki-platform-export/xwiki-platform-export-pdf/xwiki-platform-export-pdf-default/src/main/java/org/xwiki/export/pdf/internal/PDFExportConfigurationSource.java#L41) and should be used on Collabora too, starting with 14.10.

2024-10-31 08:30 UTC, oanalavinia commented on api/src/main/java/com/xwiki/identityoauth/internal/configuration/IdentityOAuthGeneralConfigurationSource.java
> + * configuration of the main wiki.
Ok, cool, I haven't thought about the fact that this app already uses 14.10 :)

2024-10-31 08:35 UTC, oanalavinia approved these changes
Just 2 small comments. Looks good otherwise :)

2024-10-31 08:35 UTC, oanalavinia commented on api/src/main/java/com/xwiki/identityoauth/configuration/IdentityOAuthGeneralConfiguration.java
> + * @since 1.7.6
Leftover

2024-10-31 08:35 UTC, oanalavinia commented on api/src/main/java/com/xwiki/identityoauth/internal/configuration/IdentityOAuthGeneralConfigurationSource.java
> +    public static final String HINT = "identity.oauth.configuration.general.current";
It's ok to specify `current` in here, given that it might not be for the current wiki?

2024-10-31 08:41 UTC, ChiuchiuSorin commented on api/src/main/java/com/xwiki/identityoauth/internal/configuration/IdentityOAuthGeneralConfigurationSource.java
> +    public static final String HINT = "identity.oauth.configuration.general.current";
Not sure if it would be better to replace `current` with `wikis`, or simply remove it. WDYT?

2024-10-31 08:51 UTC, oanalavinia commented on api/src/main/java/com/xwiki/identityoauth/internal/configuration/IdentityOAuthGeneralConfigurationSource.java
> +    public static final String HINT = "identity.oauth.configuration.general.current";
I think `identity.oauth.configuration.general` it's ok

2024-10-31 08:55 UTC, merged